# Generated by Django 3.1.1 on 2021-10-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('metal_name', models.CharField(max_length=512)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('value', models.FloatField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.metal')),
            ],
        ),
    ]
